### Testar a raiz da aplicação
GET http://localhost:5233

### Listar produtos
GET http://localhost:5233/produto/listar

### Cadastrar produto
POST http://localhost:5233/produto/cadastrar/
Content-Type: application/json 

{
    "nome" : "Bolacha", 
    "preco": 3.2,
    "quantidade": 534
}

###

### Buscar produto
GET http://localhost:5233/produto/buscar/eba33668-ad72-45d0-b7f1-8fbfef7ab2d1

### Testar a quarta funcionalidade
GET http://localhost:5233/receber_informacao_url/Enzo

### Testar a quinta funcionalidade
POST http://localhost:5233/receber_informacao_corpo
Content-Type: application/json

{
    "Rua": "Barigui",
    "Numero": 3500,
    "Cep": "01310-200"
}
